[package]
name = "icon_windows"
version = "0.1.0"
edition = "2021"

[features]
default = ["auto", "ico", "png", "xxx", "xcf", "svg", "placeholder", "embed_resource"]
build_cfg=["dep:build_cfg"]
embed_resource=["dep:embed-resource"]
ico = []
png = ["ico"]
xxx = ["png"]
svg = ["xxx"]
xcf = ["xxx"]
placeholder = ["svg"]
auto = []

[dependencies]
build_cfg = { version = "1.1.0", optional = true }
embed-resource = { version = "1.8.0", optional = true }